// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNqy8xqXturT94RI2SQuQPZhaP4XKJAmY',
    appId: '1:447226478916:web:8028b4d44b67a4fbd65711',
    messagingSenderId: '447226478916',
    projectId: 'smashtest-001',
    authDomain: 'smashtest-001.firebaseapp.com',
    storageBucket: 'smashtest-001.appspot.com',
    measurementId: 'G-1BY3SHWB7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBp9lhTqX0Uj5RYZe-2RoHaUIqXlxju2w',
    appId: '1:447226478916:android:d753e93a0a27f9c2d65711',
    messagingSenderId: '447226478916',
    projectId: 'smashtest-001',
    storageBucket: 'smashtest-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAveCHBZbxAOO7QSVQ74QVGGxM96CukcBA',
    appId: '1:447226478916:ios:b8006f5f96bbb3edd65711',
    messagingSenderId: '447226478916',
    projectId: 'smashtest-001',
    storageBucket: 'smashtest-001.appspot.com',
    iosClientId: '447226478916-hi6kbipbobapp1jsvbt7jsf61a9gegr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smash',
  );
}
